baseURL = 'https://eai.company/'
languageCode = 'en-us'
title = 'EnlightenmentAI'
theme = 'eai'

# Main menu configuration
[menu]
  [[menu.main]]
    name = "Hire Us"
    url = "https://cal.com/datastrategy"
    weight = 1

# Links
[params]
  consultation_link = "https://cal.com/datastrategy"
  upwork_link = "https://www.upwork.com/freelancers/~01e011c914ffcb10f8"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'