baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'EnlightenmentAI'
theme = 'eai'

# Main menu configuration
[menu]
  [[menu.main]]
    name = "Trusted By"
    url = "#trustedby"
    weight = 1
  [[menu.main]]
    name = "Insights"
    url = "#insights"
    weight = 2
  [[menu.main]]
    name = "Hire Us"
    url = "#hire-us"
    weight = 3

# Links
[params]
  consultation_link = "https://cal.com/datastrategy"


[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'